# we can set active profile from here as well no need to pass at run time
spring:
  profiles:
# if native is active then you can't use any repository file data
#    active: native
    active: config.server.station,eureka,security
#    active: config.server,eureka,security
#    active: config.server,eureka,admin,logging
#  main:
#    banner-mode: "off"

# info property details shows in actuators info url http://localhost:8701/actuator/info
info:
  name: '@project.artifactId@'
  description: '@project.description@'
  version: '@project.version@'
  id: cfg
  artifactId: '@project.artifactId@'
  packaging: '@project.packaging@'
  groupId: '@project.groupId@'
  