info:
  name: '@project.artifactId@'
  description: '@project.description@'
  version: '@project.version@'

management:
  security:
    enabled: false
 
spring:
  cloud: 
    config:
      server:
        git:
#        If you are using local repository!
          uri: file:///S:/repository/config-repository
#        If you are using cloud repository!
#          uri: https://github.com/singhmahabir/config-repository

          searchPaths: config
          
# If you are using Admin server and want to registered your application as Admin client then add below configuration. 
#  boot:
#    admin:
#      url: http://localhost:1111
#      username: admin
#      password: admin123
#    

# If you are using registry server and want config-client access configuration via registry server then use.
#eureka: 
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8760/eureka/
#  instance:
#        preferIpAddress: true

